services:
  translation-llm:
    image: ${OLLAMA_IMAGE}
    restart: unless-stopped
    ports:
      - ${OLLAMA_BIND}:11434
    volumes:
      - ollama-models:/root/.ollama

  model-loader:
    image: ${OLLAMA_IMAGE}
    depends_on:
      - translation-llm
    environment:
      - OLLAMA_HOST= http://translation-llm:11434
    command: [ "pull", "${LCB_TRANSLATION_MODEL}" ]

volumes:
  ollama-models:
